language: python
python:
  - "3.4"
  - "3.5"

env:
  - DJANGO_SETTINGS_MODULE=webshark.settings
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - python manage.py test
notifications:
  slack: web-shark:XvvW4b1nPjM3kUfXbIboQrtk
