# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0002_auto_20160702_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packet',
            name='date',
        ),
    ]
